Repository wecode-bootcamp-korea/17-1st-200store-frontend, pull requests merged in 2021-02, with the labels that each got.

#9 [17기 서유진] Nav Branch에 파일 분리하기
  public/images/index/favicon.ico
  public/images/index/logo.png
  public/images/nav/logo.png
  public/index.html
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/navData.js
Labels: Status: Accepted

#10 [17기 서유진] Footer Branch에 파일 분리하기
  public/images/footer/footerlogo.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
Labels: Status: Accepted

#3 [17기 서유진] 메인페이지 컴포넌트로 분리하기 피드백 반영 완료
  .eslintrc.json
  package-lock.json
  public/data/mainData.json
  src/Pages/Cart/Cart.js
  src/Pages/Main/Components/GiftBox/GiftBox.js
  src/Pages/Main/Components/GiftBox/GiftBox.scss
  src/Pages/Main/Components/ProductBox/ProductBox.js
  src/Pages/Main/Components/ProductBox/ProductBox.scss
  src/Pages/Main/Components/ProductContainer/ProductContainer.js
  src/Pages/Main/Components/ProductContainer/ProductContainer.scss
  src/Pages/Main/Components/Slider/Slider.js
  src/Pages/Main/Components/Slider/Slider.scss
  src/Pages/Main/Components/Slider/sliderData.js
  src/Pages/Main/GiftBoxData.js
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/Payment/Payment.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductList/ProductList.js
  src/Pages/Signup/Signup.js
  src/Styles/reset.scss
  src/index.js
  src/index.scss
Labels: Status: 리뷰 진행중

#11 [17기 이미경] 회원가입 리뷰반영 리팩토링 완료 및 컴플릭트 해결
  package-lock.json
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/config.js
Labels: Status: 리뷰 요청

#13 [17기 서유진] 장바구니 컴포넌트로 분리하기, 전체선택 기능 구현
  public/data/cartListData.json
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/Components/CartItem/CartItem.js
  src/Pages/Cart/Components/CartItem/CartItem.scss
  src/Pages/Cart/Components/CartList/CartList.js
  src/Pages/Cart/Components/CartList/CartList.scss
  src/Pages/Cart/Components/CartPrice/CartPrice.js
  src/Pages/Cart/Components/CartPrice/CartPrice.scss
  src/Pages/Main/Main.js
Labels: Status: Accepted

#4 [17기 김연주] 로그인 레이아웃 완성 및 수정중
  package-lock.json
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#5 [17기 이미경] 상품 디테일 페이지 컴포넌트화 및 리팩토링 수정 완료
  public/data/productdetaildata.json
  public/data/productimages.json
  public/data/productview.json
  public/data/reviewdata.json
  src/Pages/ProductDetail/Components/Itemgoodstab.js
  src/Pages/ProductDetail/Components/Modal.js
  src/Pages/ProductDetail/Components/Modal.scss
  src/Pages/ProductDetail/Components/admin_msg.js
  src/Pages/ProductDetail/Components/itemphotoinfosec.js
  src/Pages/ProductDetail/Components/productdetailtable.js
  src/Pages/ProductDetail/Components/review.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
Labels: Status: Accepted

#17 [17기 이미경] 메인 & 상품 디테일 페이지 동적 라우팅 기능 완료
  package-lock.json
  src/Pages/Main/Components/ProductBox/ProductBox.js
  src/Pages/Main/Components/ProductContainer/ProductContainer.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/Components/itemphotoinfosec.js
  src/Pages/ProductDetail/Components/review.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Routes.js
Labels: Status: Accepted

#20 [17 장성준] eslint 수정
  .eslintrc.json
Labels: Status: 리뷰 요청

#21 [17기 이미경] 상품디테일 페이지 맵 기능 수정 및 컴플릭트 해결 완료
  .eslintrc.json
  package-lock.json
  src/Pages/Main/Components/ProductBox/ProductBox.js
  src/Pages/ProductDetail/ProductDetail.js
Labels: Status: Accepted

#22 [17기 이미경] 상품디테일 페이지 댓글 기능 추가 및 컴플릭트 해결 완료
  package-lock.json
  src/Pages/ProductDetail/Components/review.js
  src/Pages/ProductDetail/ProductDetail.scss
Labels: Status: 리뷰 요청

#12 [17 김연주] 추가 기능, 리뷰 반영 완료
  public/ProductList.json
  public/ProductListData.json
  public/index.html
  src/Components/Nav/Nav.js
  src/Pages/Main/Components/ProductBox/ProductBox.js
  src/Pages/ProductList/Components/Product.js
  src/Pages/ProductList/Components/Product.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Routes.js
  src/config.js
Labels: Status: Accepted

#16 [17기 서유진] 마이페이지 백앤드와 통신 함수 수정
  package-lock.json
  package.json
  public/data/orderData.json
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Components/CartItem/CartItem.scss
  src/Pages/Cart/Components/CartList/CartList.scss
  src/Pages/Cart/Components/CartPrice/CartPrice.scss
  src/Pages/Login/Login.js
  src/Pages/MyPage/Components/Modal.js
  src/Pages/MyPage/Components/Modal.scss
  src/Pages/MyPage/Components/OrderHistory/Components/Calendar/Calendar.js
  src/Pages/MyPage/Components/OrderHistory/Components/Calendar/Calendar.scss
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/Components/OrderListItemWrapper/Components/OrderListItem.js
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/Components/OrderListItemWrapper/Components/OrderListItem.scss
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/OrderList.js
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/OrderList.scss
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/OrderListContainer.js
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/OrderListContainer.scss
  src/Pages/MyPage/Components/OrderHistory/OrderHistory.js
  src/Pages/MyPage/Components/OrderHistory/OrderHistory.scss
  src/Pages/MyPage/Components/OrderHistory/react-datepicker.css
  src/Pages/Signup/Signup.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#15 [17기 서유진] 결제페이지 리팩토링 완료
  config.js
  package-lock.json
  package.json
  public/data/paymentData.json
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/MyPage/Components/CurrentOrder/CurrentOrder.js
  src/Pages/MyPage/Components/CurrentOrder/CurrentOrder.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/Payment/Components/BuyerInfo/BuyerInfo.js
  src/Pages/Payment/Components/BuyerInfo/BuyerInfo.scss
  src/Pages/Payment/Components/DeliveryInfo/DeliveryInfo.js
  src/Pages/Payment/Components/DeliveryInfo/DeliveryInfo.scss
  src/Pages/Payment/Components/PaymentInfo/PaymentInfo.js
  src/Pages/Payment/Components/PaymentInfo/PaymentInfo.scss
  src/Pages/Payment/Payment.js
  src/Pages/Payment/Payment.scss
  src/config.js
Labels: Status: 컨플릭트 해결 요청

#25 [17기 서유진] scss 수정 및 통신함수 수정
  src/Components/Nav/Nav.js
  src/Pages/Cart/Cart.js
  src/Pages/MyPage/Components/Aside/MyPageAside.js
  src/Pages/MyPage/Components/Aside/MyPageAside.scss
  src/Pages/MyPage/Components/CurrentOrder/CurrentOrder.js
  src/Pages/MyPage/Components/CurrentOrder/CurrentOrder.scss
  src/Pages/MyPage/Components/Header/MyPageHeader.js
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/Components/OrderListItemWrapper/Components/OrderListItem.js
  src/Pages/MyPage/Components/OrderHistory/Components/OrderListContainer/Components/Components/OrderListItemWrapper/Components/OrderListItem.scss
  src/Pages/MyPage/Components/OrderHistory/OrderHistory.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPage.scss
  src/Pages/Payment/Payment.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/Signup/Signup.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#27 [17기 이미경] CSS 상품 디테일 컴플릭트 수정 완료
  src/Pages/ProductDetail/Components/itemphotoinfosec.js
  src/Pages/ProductDetail/ProductDetail.scss
Labels: Status: 리뷰 요청

#26 [17기 김연주] Login click함수 추가구현
  src/Pages/Login/Login.js
Labels: Status: 리뷰 요청

#29 [17기 김연주 ] Login페이지 scss수정
  src/Pages/Login/Login.scss
Labels: Status: 리뷰 요청

#28 [17기 서유진] 백앤드 통신 함수 수정중
  public/images/main/200store.jpg
  src/Pages/Cart/Cart.js
  src/Pages/Login/Login.js
  src/Pages/Main/Components/Slider/sliderData.js
  src/Pages/MyPage/Components/OrderHistory/OrderHistory.js
  src/Pages/Payment/Payment.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/Signup/Signup.js
  src/config.js
Labels: Status: 리뷰 요청
